package pl.edu.pw.mini.mg1.layout;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pl.edu.pw.mini.mg1.models.BezierC0;

import javax.swing.*;
import java.awt.*;

public class BezierLayout implements Controller<BezierC0> {
    private JPanel mainPane;
    private JCheckBox showPolyLineCheckBox;
    private BezierC0 bezier;

    public BezierLayout() {
        $$$setupUI$$$();
        showPolyLineCheckBox.addActionListener(e -> {
            if (bezier == null) return;
            bezier.setShowPolyline(showPolyLineCheckBox.isSelected());
        });
    }

    @Override
    public void set(BezierC0 bezier) {
        this.bezier = bezier;
        refresh();
    }

    @Override
    public Container getMainPane() {
        return mainPane;
    }

    @Override
    public void refresh() {
        if (bezier == null) {
            showPolyLineCheckBox.setSelected(false);
        } else {
            showPolyLineCheckBox.setSelected(bezier.isShowPolyline());
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        showPolyLineCheckBox = new JCheckBox();
        showPolyLineCheckBox.setText("show poly-line");
        mainPane.add(showPolyLineCheckBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPane.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
