package pl.edu.pw.mini.mg1.layout;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pl.edu.pw.mini.mg1.models.IntersectionCurve;

import javax.swing.*;
import java.awt.*;

public class IntersectionCurveController implements Controller<IntersectionCurve> {
    private JButton paramsSpaceButton;
    private JPanel mainPane;
    private JCheckBox pRightSideCheckBox;
    private JCheckBox pLeftSideCheckBox;
    private JCheckBox qRightSideCheckBox;
    private JCheckBox qLeftSideCheckBox;
    private JCheckBox asInterpolationCurveCheckBox;

    private IntersectionCurve curve;

    public IntersectionCurveController() {
        $$$setupUI$$$();
        paramsSpaceButton.addActionListener(e -> new ParametersSpaceLayout(curve));
        pRightSideCheckBox.addActionListener(e -> curve.getP().setRightSide(pRightSideCheckBox.isSelected()));
        pLeftSideCheckBox.addActionListener(e -> curve.getP().setLeftSide(pLeftSideCheckBox.isSelected()));
        qRightSideCheckBox.addActionListener(e -> curve.getQ().setRightSide(qRightSideCheckBox.isSelected()));
        qLeftSideCheckBox.addActionListener(e -> curve.getQ().setLeftSide(qLeftSideCheckBox.isSelected()));
        asInterpolationCurveCheckBox.addActionListener(e -> curve.setShowInterCurve(asInterpolationCurveCheckBox.isSelected()));
    }

    @Override
    public void set(IntersectionCurve curve) {
        this.curve = curve;
        refresh();
    }

    @Override
    public Container getMainPane() {
        return mainPane;
    }

    @Override
    public void refresh() {
        if (curve == null) return;
        pRightSideCheckBox.setSelected(curve.getP().isRightSide());
        pLeftSideCheckBox.setSelected(curve.getP().isLeftSide());
        qRightSideCheckBox.setSelected(curve.getQ().isRightSide());
        qLeftSideCheckBox.setSelected(curve.getQ().isLeftSide());
        qRightSideCheckBox.setEnabled(curve.getP() != curve.getQ());
        qLeftSideCheckBox.setEnabled(curve.getP() != curve.getQ());
        asInterpolationCurveCheckBox.setSelected(curve.isShowInterCurve());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new javax.swing.JPanel();
        mainPane.setLayout(new GridLayoutManager(7, 1, new java.awt.Insets(0, 0, 0, 0), -1, -1));
        paramsSpaceButton = new javax.swing.JButton();
        mainPane.add(paramsSpaceButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPane.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        pRightSideCheckBox = new javax.swing.JCheckBox();
        mainPane.add(pRightSideCheckBox, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pLeftSideCheckBox = new javax.swing.JCheckBox();
        mainPane.add(pLeftSideCheckBox, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        qRightSideCheckBox = new javax.swing.JCheckBox();
        mainPane.add(qRightSideCheckBox, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        qLeftSideCheckBox = new javax.swing.JCheckBox();
        mainPane.add(qLeftSideCheckBox, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        asInterpolationCurveCheckBox = new javax.swing.JCheckBox();
        mainPane.add(asInterpolationCurveCheckBox, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public javax.swing.JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
