package pl.edu.pw.mini.mg1.layout;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pl.edu.pw.mini.mg1.models.Patch;

import javax.swing.*;
import java.awt.*;

public class PatchController implements Controller<Patch> {
    private JPanel mainPane;
    private JCheckBox showBezierMeshCheckBox;
    private JSpinner divisionsUSpinner;
    private JSpinner divisionsVSpinner;
    private Patch patch;

    public PatchController() {

        showBezierMeshCheckBox.addActionListener(e -> {
            if (patch == null) return;
            patch.setShowBezierMesh(showBezierMeshCheckBox.isSelected());
        });

        divisionsUSpinner.setModel(new SpinnerNumberModel(2, 2, 100, 1));
        divisionsVSpinner.setModel(new SpinnerNumberModel(2, 2, 100, 1));

        divisionsUSpinner.addChangeListener(change -> {
            if (patch == null) return;
            patch.setDivisionsU(((Number) divisionsUSpinner.getValue()).intValue());
        });

        divisionsVSpinner.addChangeListener(change -> {
            if (patch == null) return;
            patch.setDivisionsV(((Number) divisionsVSpinner.getValue()).intValue());
        });

    }

    @Override
    public void set(Patch patch) {
        this.patch = patch;
        refresh();
    }

    @Override
    public Container getMainPane() {
        return mainPane;
    }

    @Override
    public void refresh() {
        if (patch == null) return;
        divisionsUSpinner.setValue(patch.getDivisionsU());
        divisionsVSpinner.setValue(patch.getDivisionsV());
        showBezierMeshCheckBox.setSelected(patch.isShowBezierMesh());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        showBezierMeshCheckBox = new JCheckBox();
        showBezierMeshCheckBox.setText("show bezier mesh");
        mainPane.add(showBezierMeshCheckBox, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPane.add(spacer1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("divisionsU");
        mainPane.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        divisionsUSpinner = new JSpinner();
        mainPane.add(divisionsUSpinner, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("divisionsV");
        mainPane.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        divisionsVSpinner = new JSpinner();
        mainPane.add(divisionsVSpinner, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
