package pl.edu.pw.mini.mg1.layout;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pl.edu.pw.mini.mg1.milling.Path;
import pl.edu.pw.mini.mg1.milling.PathGenerator;
import pl.edu.pw.mini.mg1.models.Scene;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class PathGenerationController implements Controller<Scene> {
    private JButton generate1Button;
    private JButton generate2Button;
    private JButton generate3Button;
    private JButton generate4Button;
    private JPanel mainPane;
    private Scene scene;

    public PathGenerationController() {
        generate1Button.addActionListener(e -> {
            Path path = PathGenerator.generate1(scene);
            save(path, "1.k16");
        });
        generate2Button.addActionListener(e -> {
            Path path = PathGenerator.generate2(scene);
            save(path, "2.f12");
        });
        generate3Button.addActionListener(e -> {
            Path path = PathGenerator.generate3(scene);
            save(path, "3.f10");
        });
        generate4Button.addActionListener(e -> {
            Path path = PathGenerator.generate4(scene);
            save(path, "1.k08");
        });
    }

    public void save(Path path, String filename) {
        try {
            Files.writeString(new File(filename).toPath(), path.toString());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void set(Scene scene) {
        this.scene = scene;
    }

    @Override
    public Container getMainPane() {
        return mainPane;
    }

    @Override
    public void refresh() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        generate1Button = new JButton();
        generate1Button.setText("Generate 1");
        mainPane.add(generate1Button, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPane.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        generate2Button = new JButton();
        generate2Button.setText("Generate 2");
        mainPane.add(generate2Button, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generate3Button = new JButton();
        generate3Button.setText("Generate 3");
        mainPane.add(generate3Button, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generate4Button = new JButton();
        generate4Button.setText("Generate 4");
        mainPane.add(generate4Button, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
